spring:
  application:
    name: resolva-ja-api
  datasource:
    url: jdbc:postgresql://localhost:5432/resolvadb
    username: resolvauser
    password: resolvapass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /tmp/uploads
security:
  jwt:
    secret: qCi5HkGeYaaqErkLT54G76MKOHGkltsS
    expiration: 3600000



